
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.numeric_std.all;
use work.typedefs.all;

-- mixer to add pcm data generated by a configurable number (see typedefs.vhdl) of waveform generators.
-- not described as balanced tree adder to allow for channel numbers not equal 2^n


entity Mixer is
    Port ( PCM_IN_VECT : in mix_pcm_vector_t;
           PCM_OUT : out pcm_data_t;
           reset : in STD_LOGIC;
           CLK : in STD_LOGIC;
           CE : in STD_LOGIC);
end Mixer;

architecture Behavioral of Mixer is


begin 
process(clk)
    variable pcm_buffer : pcm_data_t := to_pcm_data_t(0);
begin
    if rising_edge(CLK)
    then
        if CE='1'
        then
            pcm_buffer:=to_pcm_data_t(0);
            for i in mix_channel_count -1 downto 0 loop
                    pcm_buffer := pcm_buffer+PCM_IN_VECT(i);
            end loop;
            PCM_OUT<=pcm_buffer;
        end if;
    end if;
end process;
end Behavioral;
